profile: null
region: ap-northeast-1
versioning: false
default_alias: null
clean_build: false
configuration:
  name: {{ENV_PREFIX}}ci-lamvery
  runtime: python2.7
  role: arn:aws:iam::713403314913:role/{{ROLE}}
  handler: lambda_function.lambda_handler
  description: lamvery ci test
  timeout: 10
  memory_size: 128
  vpc_config:
